# Docker Compose override for development environment
# This file uses volumes to mount local code for hot-reload development

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      # Mount frontend source code for hot-reload
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - NODE_ENV=development
      #      - NUXT_PUBLIC_API_BASE_URL=http://localhost:9221/api
    command: npm run dev
    ports:
      - "${FRONTEND_PORT}:9122"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # Mount entire backend code for development
      - ./backend:/var/www/html
      # Exclude vendor directory to use container's dependencies
      - /var/www/html/vendor
      # Persistent storage
      - ./backend/storage:/var/www/html/storage
      - backend_bootstrap_cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:${BACKEND_PORT}
      # Add CORS settings for local development
      - CORS_ALLOWED_ORIGINS=http://localhost:${FRONTEND_PORT},http://localhost:3000,http://localhost:${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:8000"
    command: /startup.sh

  mysql:
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_2024
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  redis:
    ports:
      - "${REDIS_PORT}:6379"

  phpmyadmin:
    ports:
      - "${PHPMYADMIN_PORT}:80"

volumes:
  backend_bootstrap_cache:
    driver: local